[project]
name = "ai-employee-vault"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-api-python-client>=2.188.0",
    "playwright>=1.57.0",
    "watchdog>=6.0.0",
]
